//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_in_detail
    {
        public int id { get; set; }
        public Nullable<int> id_bill_in { get; set; }
        public Nullable<int> id_book { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual bill_in bill_in { get; set; }
        public virtual book book { get; set; }
    }
}
