//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.agent_payment_detail = new HashSet<agent_payment_detail>();
            this.agent_storage = new HashSet<agent_storage>();
            this.bill_in_detail = new HashSet<bill_in_detail>();
            this.bill_out_detail = new HashSet<bill_out_detail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int id_cat { get; set; }
        public int id_nxb { get; set; }
        public string author { get; set; }
        public double price { get; set; }
        public double price_in { get; set; }
        public int stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agent_payment_detail> agent_payment_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agent_storage> agent_storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_in_detail> bill_in_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_out_detail> bill_out_detail { get; set; }
        public virtual cat cat { get; set; }
        public virtual publisher publisher { get; set; }
    }
}
